import type { ModelToolResponse, ProjectListResponse, ProjectSetResponse, TemplatePreviewResponse, WorkflowSavePayload, WorkflowSaveResponse } from "../types/domain.js";
export declare function fetchJSON<T = any>(url: string, opts?: RequestInit): Promise<T>;
export declare function tryResolveProjectId(folder: string): Promise<string>;
export declare function listProjects(): Promise<ProjectListResponse>;
export declare function setProject(project_name: string, create_base?: boolean): Promise<ProjectSetResponse>;
export declare function getModels(): Promise<ModelToolResponse>;
export declare function createCustomOut(payload: Record<string, unknown>): Promise<TemplatePreviewResponse>;
export declare function previewTemplate(template: string, tokens: Record<string, unknown>): Promise<TemplatePreviewResponse>;
export declare function listExistingNames(project_id: string, media?: string): Promise<string[]>;
export declare function saveWorkflow(payload: WorkflowSavePayload): Promise<WorkflowSaveResponse>;
export declare function scanModelCandidates(missing: unknown[]): Promise<ModelToolResponse>;
export declare function resolveModelRecipes(missing: unknown[]): Promise<ModelToolResponse>;
export declare function saveModelRecipes(items: unknown[]): Promise<ModelToolResponse>;
export declare function downloadModels(items: unknown[]): Promise<ModelToolResponse>;
export declare function getDownloadStatus(job_id: string): Promise<ModelToolResponse>;
export declare function getFingerprintCacheStatus(): Promise<ModelToolResponse>;
export declare function buildFingerprintCache(payload: Record<string, unknown>): Promise<ModelToolResponse>;
export declare function resolveFingerprint(payload: Record<string, unknown>): Promise<ModelToolResponse>;
export declare function searchRegistry(query: string, limit?: number): Promise<ModelToolResponse>;
export declare function contributeRegistry(payload: Record<string, unknown>): Promise<ModelToolResponse>;
