export declare const DEFAULT_STATE: {
    projectName: string;
    workflowName: string;
    workflowAsset: string;
    workflowLastBase: string;
    workflowNextSuffix: number;
    workflowPanelOpen: boolean;
    projectId: string;
    projectFolder: string;
    projectExists: any;
    autoPatch: boolean;
    autoPatchNewNodes: boolean;
    autoSwitchTrusted: boolean;
    autoHookSave: boolean;
    kind: string;
    media: string;
    name: string;
    modelSelection: string;
    detectedModelTag: string;
    useCustomModel: boolean;
    customModelText: string;
    modelUpper: boolean;
    pendingProjectName: string;
    pendingSelectProjectId: string;
    lastRelDir: string;
    lastPrefix: string;
    pathTemplate: string;
    showMoreModels: boolean;
    lastError: string;
    detected: any;
    workflowHasSignature: boolean;
    workflowChecked: boolean;
    isGraphLoading: boolean;
    graphLoadToken: number;
    graphIsEmpty: boolean;
};
export declare let runtimeState: any;
export declare function setRuntimeState(state: any): void;
export declare function createRuntimeState(overrides: any): any;
export declare function loadState(): any;
export declare function saveState(state: any): void;
