export declare function fetchJSON(url: any, opts: any): Promise<any>;
export declare function tryResolveProjectId(folder: any): Promise<any>;
export declare function listProjects(): Promise<any>;
export declare function setProject(project_name: any, create_base?: boolean): Promise<any>;
export declare function getModels(): Promise<any>;
export declare function createCustomOut(payload: any): Promise<any>;
export declare function previewTemplate(template: any, tokens: any): Promise<any>;
export declare function listExistingNames(project_id: any, media?: string): Promise<any>;
export declare function saveWorkflow(payload: any): Promise<any>;
export declare function scanModelCandidates(missing: any): Promise<any>;
export declare function resolveModelRecipes(missing: any): Promise<any>;
export declare function saveModelRecipes(items: any): Promise<any>;
export declare function downloadModels(items: any): Promise<any>;
export declare function getDownloadStatus(job_id: any): Promise<any>;
export declare function getFingerprintCacheStatus(): Promise<any>;
export declare function buildFingerprintCache(payload: any): Promise<any>;
export declare function resolveFingerprint(payload: any): Promise<any>;
export declare function searchRegistry(query: any, limit?: number): Promise<any>;
export declare function contributeRegistry(payload: any): Promise<any>;
